//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: sifnode/tokenregistry/v1/query.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Query defines the gRPC querier service.
///
/// Usage: instantiate `Sifnode_Tokenregistry_V1_QueryClient`, then call methods of this protocol to make API calls.
internal protocol Sifnode_Tokenregistry_V1_QueryClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Sifnode_Tokenregistry_V1_QueryClientInterceptorFactoryProtocol? { get }

  func entries(
    _ request: Sifnode_Tokenregistry_V1_QueryEntriesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Sifnode_Tokenregistry_V1_QueryEntriesRequest, Sifnode_Tokenregistry_V1_QueryEntriesResponse>
}

extension Sifnode_Tokenregistry_V1_QueryClientProtocol {
  internal var serviceName: String {
    return "sifnode.tokenregistry.v1.Query"
  }

  /// Unary call to Entries
  ///
  /// - Parameters:
  ///   - request: Request to send to Entries.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func entries(
    _ request: Sifnode_Tokenregistry_V1_QueryEntriesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Sifnode_Tokenregistry_V1_QueryEntriesRequest, Sifnode_Tokenregistry_V1_QueryEntriesResponse> {
    return self.makeUnaryCall(
      path: "/sifnode.tokenregistry.v1.Query/Entries",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEntriesInterceptors() ?? []
    )
  }
}

internal protocol Sifnode_Tokenregistry_V1_QueryClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'entries'.
  func makeEntriesInterceptors() -> [ClientInterceptor<Sifnode_Tokenregistry_V1_QueryEntriesRequest, Sifnode_Tokenregistry_V1_QueryEntriesResponse>]
}

internal final class Sifnode_Tokenregistry_V1_QueryClient: Sifnode_Tokenregistry_V1_QueryClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Sifnode_Tokenregistry_V1_QueryClientInterceptorFactoryProtocol?

  /// Creates a client for the sifnode.tokenregistry.v1.Query service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Sifnode_Tokenregistry_V1_QueryClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Query defines the gRPC querier service.
///
/// To build a server, implement a class that conforms to this protocol.
internal protocol Sifnode_Tokenregistry_V1_QueryProvider: CallHandlerProvider {
  var interceptors: Sifnode_Tokenregistry_V1_QueryServerInterceptorFactoryProtocol? { get }

  func entries(request: Sifnode_Tokenregistry_V1_QueryEntriesRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Sifnode_Tokenregistry_V1_QueryEntriesResponse>
}

extension Sifnode_Tokenregistry_V1_QueryProvider {
  internal var serviceName: Substring { return "sifnode.tokenregistry.v1.Query" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "Entries":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Sifnode_Tokenregistry_V1_QueryEntriesRequest>(),
        responseSerializer: ProtobufSerializer<Sifnode_Tokenregistry_V1_QueryEntriesResponse>(),
        interceptors: self.interceptors?.makeEntriesInterceptors() ?? [],
        userFunction: self.entries(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Sifnode_Tokenregistry_V1_QueryServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'entries'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeEntriesInterceptors() -> [ServerInterceptor<Sifnode_Tokenregistry_V1_QueryEntriesRequest, Sifnode_Tokenregistry_V1_QueryEntriesResponse>]
}
